version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'transfer'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  transfer_app:
    build: ./
    ports:
      - '5500:5500'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/transfer
    depends_on:
      - db